### ISSUE TITLE
Configure popup behavior

### ISSUE THREAD

**Issue by danielpeintner** [niccokunzmann/open-web-calendar#447]
According to https://open-web-calendar.hosted.quelltext.eu/ there is no option to configure the popup behavior e.g., 
* show popup at all (yes/no)
* show popup on mouse over  (yes/no)
* show popup on click  (yes/no)
* show popup on day&month view and not on month view
* ...

Do you plan to allow this kind of configuration in the future?

**Comment by niccokunzmann** [comment]
Thanks, that can be arranged. I do that in my spare time. If you fund the issue, I can prioritize it more.

I had a look at https://github.com/w3c/wot-marketing/issues/497 - please feel free to create more issues in this repository. This way, we can discuss and rank features as well as fix simple things fast.

**Comment by niccokunzmann** [comment]
Hello, the pop-up behaviour can now be changed! Not in the UI, yet but in the specification.

```yaml
## Activate and deactivate plugins
## The event details are shown when you click on the event.
plugin_event_details: true
## When the mouse moves over an event, this tooltip is shown
## Note: This is only available on non-touch devices
##       Even if the values is true.
plugin_event_tooltip: true
```

I have not added a way to selectively add this according to the view you are on. I guess, this is what it takes to close this.
